"""Generate a 100-file markdown knowledge base on AI infrastructure: Products, Harness,
Runtime, Eval, Observability (20 real, distinct topics each) — for the retrieval/rerank demo.

Filenames are neutral (doc_NNN.md, shuffled) and ground truth lives in a separate manifest —
never in the filename or the doc content itself — so the category can't be guessed from the
file list.
"""
import json
import random
from pathlib import Path

random.seed(66)
ROOT = Path(__file__).parent
OUT = ROOT / "kb_docs"
OUT.mkdir(exist_ok=True)

KB = {
    "products": [
        ("Customer support chatbots", "AI agents embedded in help centers or chat widgets that resolve tickets end to end — answering FAQs, pulling order status from backend systems, and escalating to a human only when confidence is low. Success is measured by deflection rate (tickets resolved without a human) and CSAT, not just accuracy."),
        ("AI coding assistants", "Inline pair-programming tools (Copilot-style) that suggest completions, whole functions, or multi-file edits inside the editor. The best ones use the open files, recent edits, and repo structure as context, and increasingly run in an agentic loop that edits, runs tests, and iterates rather than a single autocomplete suggestion."),
        ("AI answer/search engines", "Search products that return a synthesized answer with citations instead of a list of links, usually backed by retrieval-augmented generation over a live index. The hard part is grounding every claim in a retrieved source so the answer can be verified, not just fluent."),
        ("Recommendation engines", "Systems that rank items (products, videos, posts) for a specific user using behavioral signals. LLM-based recommenders increasingly blend classical collaborative filtering with semantic understanding of item descriptions, letting them handle cold-start items with no interaction history."),
        ("Content moderation products", "Products that classify user-generated content against a platform's policy — hate speech, spam, nudity, self-harm — often as a first-pass filter feeding a human review queue. Precision/recall tradeoffs matter enormously: over-flagging erodes trust, under-flagging creates liability."),
        ("AI writing assistants", "Tools that draft, rewrite, or edit text to a target tone and length — emails, marketing copy, documentation. Differentiation comes from house-style adherence (brand voice) and integration into where people already write, not raw generation quality."),
        ("Image generation products", "Consumer and API products wrapping diffusion or autoregressive image models, usually with a control layer (reference images, masks, style presets) on top of a raw model to make output predictable enough for commercial use like ad creative or product mockups."),
        ("Voice assistants", "Spoken-language interfaces that chain speech-to-text, an LLM, and text-to-speech (or use a native speech-to-speech model) to hold a real-time conversation. Latency budget is the defining constraint — anything over ~300ms round-trip starts to feel unnatural."),
        ("AI meeting summarizers", "Tools that transcribe a call and extract a structured summary — decisions, action items, owners — rather than a flat transcript. Speaker diarization accuracy and correctly attributing action items to the right person are the recurring failure modes."),
        ("Document Q&A / RAG products", "Products that let a user ask questions over their own documents (contracts, manuals, wikis) by retrieving relevant chunks and grounding the answer in them. Chunking strategy and retrieval quality dominate answer quality far more than the generation model itself."),
        ("Autonomous coding agents", "Agents that take a ticket or bug report and independently plan, edit code across files, run the test suite, and open a pull request with minimal human steering. The gating factor is usually verification — knowing when the agent's change is actually correct."),
        ("AI customer support triage", "Systems that classify and route incoming tickets by intent, urgency, and required team before a human ever sees them, often the first AI feature support teams deploy because the ROI (reduced time-to-first-response) is easy to measure."),
        ("AI sales copilots", "Assistants embedded in a CRM that draft outreach, summarize call transcripts, and surface next-best-action for a rep, pulling context from the deal's history so suggestions are specific rather than generic sales boilerplate."),
        ("AI video generation tools", "Products that generate or edit video from text, images, or reference footage — ad creative, product demos, dubbing. Temporal consistency across frames is the core technical challenge that separates usable output from a slideshow of related images."),
        ("AI-powered analytics copilots", "Natural-language interfaces over a BI/data warehouse that translate a question into a query, run it, and explain the result. Trustworthiness hinges on the copilot showing its generated query, not just a number, so analysts can verify it."),
        ("Personalization engines for e-commerce", "Real-time systems that reorder search results, product pages, and email content per shopper based on session behavior and purchase history, typically running as a low-latency scoring service alongside the main storefront, not inside it."),
        ("AI legal document review tools", "Products that flag risky clauses, missing terms, or deviations from a playbook across contracts, aimed at cutting first-pass review time for lawyers. False negatives (a missed risky clause) are far costlier than false positives here, so recall is prioritized."),
        ("AI medical scribes", "Ambient tools that listen to a clinician-patient visit and draft the clinical note automatically, letting the clinician review rather than write from scratch. Accuracy on medical terminology and correct attribution of symptoms to the right party are hard requirements, not nice-to-haves."),
        ("Translation/localization AI", "Products that translate UI strings, marketing copy, or support content while preserving tone, terminology consistency, and formatting (placeholders, HTML). Glossary/terminology-base integration is what separates production localization tools from a raw translation API call."),
        ("AI fraud detection products", "Systems that score transactions or accounts for fraud risk in real time, combining classical rules engines with model-based anomaly scoring. Because false positives block legitimate users, these products are tuned around cost-weighted precision, not raw accuracy."),
    ],
    "harness": [
        ("CLI coding agent harness", "A terminal-based orchestration layer (like Claude Code) that gives a model tools — file read/write, shell exec, search — and loops it against a task until done, handling permissions, context management, and session state around the raw model calls."),
        ("Agent SDK tool-use loop", "The library-level abstraction for the read-decide-act loop: pass the model a set of tool definitions, execute whichever tool call it returns, feed the result back, repeat until a stop condition. Most agent frameworks are a thin layer over this loop."),
        ("Multi-agent orchestration frameworks", "Harnesses that coordinate several specialized agents (a planner, a coder, a reviewer) with defined handoffs, as opposed to one agent doing everything. The orchestration logic — who talks to whom, in what order — is usually the actual product, not the individual agents."),
        ("Function/tool-calling harness", "The layer that turns a model's structured tool-call output into an actual function invocation, validates arguments against a schema, executes it, and serializes the result back into the conversation in the format the model expects."),
        ("Prompt chaining pipelines", "Harnesses that wire multiple discrete LLM calls into a fixed pipeline (extract, then classify, then generate) rather than one freeform agent loop — more predictable and debuggable than a fully autonomous agent, at the cost of flexibility."),
        ("Sandboxed code execution harness", "Isolated environments (containers, microVMs) where an agent can run arbitrary code it wrote without risking the host system, usually with resource limits, network restrictions, and a fresh filesystem per run."),
        ("Browser automation agent harness", "Tooling that gives an agent a controllable browser — click, type, read the DOM or a screenshot — to complete web tasks a plain API can't reach, with the accessibility tree or vision model doing the actual page understanding."),
        ("CI/CD integration harness", "The glue that lets an agent trigger builds, read test/lint output, and act on failures as part of a pipeline, turning a chat-style agent into something that participates in existing engineering workflows."),
        ("Plugin/skill systems for agents", "A registry pattern where discrete capabilities (a skill, a plugin, an MCP server) can be added to an agent without changing its core loop, letting the same harness pick up new tools without a redeploy."),
        ("Memory/context management harness", "The layer that decides what goes into the model's limited context window on each turn — summarizing old turns, retrieving relevant past state, evicting stale content — since raw conversation history alone doesn't scale past a few dozen turns."),
        ("Guardrail/policy enforcement layer", "A harness component that checks proposed agent actions (a shell command, a file write, a purchase) against a policy before executing them, independent of whether the underlying model 'wants' to do something risky."),
        ("Retry and error-recovery harness", "Logic that catches tool failures, malformed model output, or transient API errors and retries with backoff or a repaired prompt, rather than letting the whole agent run crash on the first hiccup."),
        ("Human-in-the-loop approval harness", "A checkpoint pattern where the agent pauses before an irreversible or high-stakes action and waits for explicit human confirmation, the difference between 'agent suggests' and 'agent acts unsupervised'."),
        ("Agent-to-agent protocols (MCP-style)", "Standardized interfaces (like the Model Context Protocol) that let an agent discover and call tools/resources exposed by another system without bespoke integration code for each one, the same way HTTP standardized web communication."),
        ("Task queue/scheduler harness", "Infrastructure that manages many agent runs concurrently — queuing, prioritizing, retrying, capping concurrency — so a harness built for one interactive session can scale to background batch workloads."),
        ("Testing harness for agent behavior", "A framework for running an agent against fixed scenarios and asserting on its actions/outputs, the agent-world equivalent of unit tests, needed because agent behavior can silently regress when the underlying model or prompt changes."),
        ("Cost/budget control harness", "A layer that tracks token/dollar spend per session or per user and halts or throttles an agent before it runs away — especially important for autonomous loops that could otherwise call tools or the model indefinitely."),
        ("Session/state persistence harness", "The mechanism for saving and resuming an agent's conversation, tool state, and working files across process restarts, so a long-running task survives a crash or a deliberate pause-and-resume."),
        ("Structured output enforcement", "Harness logic that constrains or validates a model's output against a schema (JSON schema, regex, grammar) so downstream code can rely on the shape of the response instead of parsing free text defensively."),
        ("Context-window packing strategy", "The harness decision of what to include, in what order, and with what priority when the accumulated context (system prompt, tool defs, history, retrieved docs) exceeds the model's window — often the single biggest lever on agent quality."),
    ],
    "runtime": [
        ("LLM inference serving", "The systems layer (vLLM, TGI, and similar) that turns a trained model into a request-serving API, handling request batching, memory management, and scheduling to maximize throughput per GPU rather than serving one request at a time."),
        ("GPU scheduling for inference", "The logic that assigns incoming requests to available GPU capacity, balancing utilization against per-request latency — packing too aggressively increases queueing delay, under-packing wastes expensive hardware."),
        ("Model quantization", "Reducing a model's numerical precision (fp16 to int8 or int4) to cut memory footprint and increase throughput, trading a small, usually acceptable accuracy loss for meaningfully cheaper and faster inference."),
        ("KV cache management", "Caching the attention key/value tensors computed for earlier tokens so generating the next token doesn't recompute them from scratch — the dominant memory cost in serving long-context requests, and the reason context length so directly drives infra cost."),
        ("Continuous batching", "A scheduling technique that adds new requests into a running batch as soon as GPU slots free up (instead of waiting for a fixed batch to fully finish), substantially raising throughput for variable-length generation workloads."),
        ("Speculative decoding", "Using a small, fast draft model to propose several tokens ahead, which the large model then verifies in parallel — sound tokens are accepted, wrong ones are recomputed — cutting latency without changing output quality."),
        ("Model routing / load balancing", "Directing each request to a specific model or provider based on cost, latency, capability, or current load — e.g. cheap requests to a small model, hard ones to a frontier model — as a runtime decision, not a build-time choice."),
        ("Edge/on-device inference", "Running a (usually quantized, distilled) model directly on a phone or embedded device instead of a server, trading capability for zero network latency, offline availability, and data staying on-device."),
        ("Serverless inference cold starts", "The latency penalty of loading a large model into GPU memory when a serverless function scales from zero, a problem specific to LLM serving because model weights are gigabytes, unlike a typical stateless web function."),
        ("Multi-model serving (model mesh)", "Infrastructure that hosts many different models behind one serving layer, dynamically loading/evicting them from GPU memory based on demand, so low-traffic models don't each need dedicated, idle hardware."),
        ("Token streaming", "Returning generated tokens to the client incrementally as they're produced rather than waiting for the full response, which is what makes a chat UI feel responsive even when total generation time is unchanged."),
        ("Prompt caching at the runtime layer", "Reusing the computed KV cache for a repeated prompt prefix (a long system prompt, a shared document) across requests so only the new suffix needs fresh computation — the mechanism behind 'cached input token' pricing discounts."),
        ("Rate limiting and quota enforcement", "Runtime controls that cap requests-per-minute or tokens-per-second per API key, protecting shared infrastructure from any single caller and giving providers a lever to manage capacity during demand spikes."),
        ("Autoscaling inference clusters", "Automatically adding or removing GPU capacity based on load, complicated by the fact that GPU instances take much longer to provision than a typical web server, so scaling has to anticipate demand rather than purely react to it."),
        ("Mixed-precision inference", "Running different parts of the computation at different numerical precisions (e.g. fp16 activations with int8 weights) to balance speed and accuracy more finely than a single blanket quantization level."),
        ("Fallback/failover across providers", "Runtime logic that automatically retries a failed or degraded request against a second model provider, treating model APIs like any other dependency that needs redundancy rather than a single point of failure."),
        ("Context window management at runtime", "Server-side truncation or rejection logic for requests that exceed a model's context limit, plus the accounting that determines how much of the window is actually usable once system prompts and reserved output space are subtracted."),
        ("Model version rollout strategies", "Canary or blue-green deployment patterns applied to model upgrades — routing a small percentage of traffic to a new model version and comparing quality/cost metrics before a full cutover, since model behavior changes are harder to unit-test than code."),
        ("Runtime cost attribution", "Tracking token usage and compute cost per request back to a specific user, feature, or customer, which is what makes usage-based pricing and per-feature cost analysis possible instead of one opaque infrastructure bill."),
        ("Distributed inference (tensor/pipeline parallelism)", "Splitting a single model too large for one GPU across multiple GPUs (or nodes), either by layer (pipeline parallelism) or within a layer (tensor parallelism), each with different communication overhead and latency tradeoffs."),
    ],
    "eval": [
        ("LLM-as-judge evaluation", "Using a strong model to score another model's outputs against a rubric, instead of exact-match or human grading — scalable and cheap, but only as reliable as the judge model's own biases and blind spots, which need separate calibration."),
        ("Golden dataset regression suites", "A fixed, curated set of input/expected-output pairs run against every model or prompt change to catch regressions, the AI equivalent of a unit test suite, usually the first eval infrastructure a team builds."),
        ("Human preference evaluation", "Having people compare two model outputs and pick the better one (the basis of RLHF-style training and leaderboards like Chatbot Arena), capturing subjective quality that automated metrics miss but expensive and slow to scale."),
        ("Automated red-teaming", "Systematically generating adversarial inputs (jailbreak attempts, edge cases, prompt injections) to probe a model or agent for failure modes before real users find them, often itself powered by another model generating the attacks."),
        ("Hallucination detection benchmarks", "Test suites specifically designed to measure how often a model states something false as fact, often by checking generated claims against a known-correct source document or knowledge base."),
        ("Task-specific accuracy benchmarks", "Narrow, well-defined benchmarks (math problem sets, coding challenges, classification datasets) that measure competence on one capability precisely, as opposed to broad general-purpose benchmarks that are easier to game or overfit to."),
        ("A/B testing model changes", "Running two model or prompt versions against live traffic and comparing business metrics (conversion, resolution rate, escalation rate), the ground-truth check that offline eval scores actually translate to real-world improvement."),
        ("Calibration and confidence evaluation", "Measuring whether a model's stated confidence (or a system's probability score) actually matches its real accuracy — a model that's right 70% of the time when it claims 70% confidence is well-calibrated, and calibration is what lets downstream code trust a threshold."),
        ("Multi-turn conversation evaluation", "Assessing quality across an entire conversation rather than a single turn — does the agent remember earlier context, avoid contradicting itself, actually resolve the user's goal — since single-turn metrics miss most real agent failure modes."),
        ("Code generation correctness eval", "Grading generated code by whether it actually passes a held-out test suite (pass@k) rather than by surface similarity to reference code, since two functionally identical solutions can look completely different."),
        ("Retrieval quality evaluation", "Measuring a RAG system's retrieval step in isolation using precision/recall/NDCG against labeled relevant documents, since a wrong or missing retrieval caps the generation step's quality no matter how good the model is."),
        ("Toxicity/safety classifiers for eval", "Automated classifiers run over model outputs at eval time to flag policy-violating content at scale, usually as a gating check before a model or prompt change can ship, not just a production-time filter."),
        ("Consistency/robustness testing", "Checking whether small, meaning-preserving changes to an input (rephrasing, typos, reordering) produce the same output — a model whose answer flips on irrelevant wording changes is fragile in a way accuracy-only metrics won't catch."),
        ("Eval-driven prompt iteration", "Using a fixed eval set as the feedback loop for improving a prompt or pipeline — change, re-run eval, compare score — turning prompt engineering from guesswork into something closer to a measurable optimization process."),
        ("Cost-normalized evaluation", "Scoring quality per dollar or per token rather than quality alone, since a marginally better model that costs 10x more is often the wrong production choice even if it wins on a raw accuracy leaderboard."),
        ("Latency/throughput benchmarking", "Measuring time-to-first-token, tokens-per-second, and end-to-end latency under realistic concurrency, a distinct axis from output quality that determines whether a model is actually usable in a latency-sensitive product."),
        ("Bias and fairness evaluation", "Testing whether a model's outputs vary systematically and unfairly across demographic groups or protected attributes, using paired/counterfactual prompts to isolate the effect of the sensitive attribute alone."),
        ("Eval dataset contamination detection", "Checking whether benchmark questions leaked into a model's training data, which would make its benchmark score meaningless — an increasingly important check as models are trained on ever-larger, less curated web-scale data."),
        ("Synthetic eval data generation", "Using a model to generate large volumes of plausible test cases (edge cases, adversarial examples, paraphrases) when hand-labeled eval data is too scarce or expensive to cover the space adequately."),
        ("Continuous eval in CI pipelines", "Running the eval suite automatically on every prompt, model, or code change as part of CI, blocking a merge if quality drops below a threshold — treating eval scores as a build gate, not a one-off report."),
    ],
    "observability": [
        ("LLM request tracing", "Capturing a full span tree for a single request across every step — retrieval, each model call, each tool invocation — so a slow or wrong response can be traced back to exactly which step caused it, the AI-pipeline equivalent of distributed tracing."),
        ("Token usage and cost dashboards", "Real-time visibility into token consumption and dollar spend broken down by model, user, or feature, the primary lever teams use to catch a runaway agent loop or an unexpectedly expensive prompt before the bill arrives."),
        ("Prompt/response logging pipelines", "Infrastructure that durably records every prompt and completion (with appropriate redaction) for later debugging, eval-set mining, and incident investigation — without this, a production issue is nearly impossible to reproduce after the fact."),
        ("Latency percentile monitoring", "Tracking p50/p95/p99 latency rather than just the average, since a handful of very slow requests (often caused by long-context prompts or a struggling downstream provider) can badly hurt user experience while barely moving the mean."),
        ("Error rate and failure alerting", "Automated alerts when API error rates, timeouts, or malformed-output rates cross a threshold, catching provider outages or a bad deploy before support tickets pile up."),
        ("Drift detection", "Monitoring whether the distribution of production inputs or outputs is shifting over time relative to what the system was built and evaluated against — a sign that offline eval numbers no longer reflect current reality."),
        ("User feedback capture loops", "Lightweight in-product signals (thumbs up/down, regeneration requests, edits) wired back into the observability pipeline so real user judgment supplements automated metrics, and often becomes new eval or training data."),
        ("Session replay for agent debugging", "Tooling that reconstructs an agent's full decision trace — every tool call, every intermediate thought, every retrieved document — in a reviewable timeline, essential for debugging an agent that went wrong three steps before the visible failure."),
        ("Anomaly detection on usage patterns", "Statistical or model-based detection of unusual request volume, cost, or content patterns that might indicate abuse, a bug, or an attack, distinct from simple threshold alerting because 'normal' usage varies a lot by time and customer."),
        ("Rate limit / quota monitoring", "Dashboards tracking how close each customer or internal service is to its rate limit or budget, letting a team proactively reach out or throttle before a hard cutoff causes a production incident."),
        ("Model output quality dashboards", "Aggregated, ongoing tracking of quality signals (eval scores, user feedback, judge-model ratings) on live traffic over time, distinct from one-off eval runs because it catches slow quality decay a single benchmark snapshot would miss."),
        ("Prompt injection detection monitoring", "Runtime scanning of inputs (and sometimes outputs) for patterns consistent with prompt injection attempts, logged and alerted on separately from generic errors since it's a security concern, not just a quality one."),
        ("Multi-provider cost comparison dashboards", "Observability that normalizes usage across multiple model providers into comparable cost and performance views, needed once a system routes across more than one vendor and a single provider's billing dashboard is no longer the full picture."),
        ("Guardrail violation logging", "Recording every time a policy/guardrail layer blocks or modifies an agent's proposed action, both for security review and to tune the guardrail itself when it's blocking too aggressively or missing real violations."),
        ("Agent tool-call audit trails", "An immutable log of every tool call an agent made, with arguments and results, required for compliance in regulated environments and invaluable for reconstructing exactly what an autonomous agent did after the fact."),
        ("Real-time hallucination spike alerting", "Monitoring that flags a sudden increase in hallucination-flagged outputs (via a judge model or user reports) as an incident, since a hallucination spike often correlates with an upstream data or retrieval problem worth investigating immediately."),
        ("Log sampling strategies", "Deciding what fraction of requests to fully log at high verbosity versus sample lightly, balancing storage/cost against the risk of missing the specific request that later turns out to matter for an investigation."),
        ("Correlation IDs across services", "Attaching a single trace ID to a request as it crosses multiple services (frontend, orchestrator, model provider, tool APIs) so logs from every hop can be joined back into one coherent timeline."),
        ("SLA/SLO tracking for AI services", "Formal tracking of whether a service meets its committed latency, uptime, and quality targets, translating fuzzy 'is the AI feature working well' into the same measurable operational discipline applied to traditional services."),
        ("Root-cause analysis tooling", "Purpose-built tooling for diagnosing why a specific agent run failed — replaying the exact context, isolating which step diverged from expected behavior — since generic APM tools weren't built for the shape of agent failures."),
    ],
}

docs = [(category, title, body) for category, items in KB.items() for title, body in items]
random.shuffle(docs)  # so sequential filenames don't cluster by category either

manifest = {}
for i, (category, title, body) in enumerate(docs, start=1):
    fname = f"doc_{i:03d}.md"
    md = f"# {title}\n\n{body}\n"
    (OUT / fname).write_text(md)
    manifest[fname] = category

(OUT / "ground_truth.json").write_text(json.dumps(manifest, indent=2))
print(f"wrote {len(manifest)} KB docs + ground_truth.json to {OUT}")
